# Generated by Django 4.1.1 on 2022-09-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeropuerto_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avion',
            name='marca',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
